
version: 2

models:
  - name: unionAll
    description: "A dbt model to union data from many SQL Server Schemas"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null

  - name: ref
    description: "A starter dbt model"
    columns:
      - name: id
        description: "The primary key for this table"
        tests:
          - unique
          - not_null
